[package]
name = "html2maud"
version = "0.1.0"
authors = ["Franco Lucchini <flucchini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "*"
markup5ever_rcdom = "*"